/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.sql.*;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {

        Class.forName("org.postgresql.Driver");
        System.out.println("Driver loaded");

        Connection conn;
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the User Name : ");
        String user_name = sc.next();
        System.out.println("Enter the Password : ");
        String pass_word = sc.next();
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test", user_name, pass_word);

        System.out.println("Coonection done");

        System.out.println("Coonection done");

        Statement stmt;
        stmt = conn.createStatement();
        System.out.println("Enter the Id : ");
        int id = sc.nextInt();
        System.out.println("Enter the Technology  : ");
        String name = sc.next();
        System.out.println("Enter the Workspace  : ");
        int ws = sc.nextInt();
        System.out.println("Enter the address : ");
        String addr = sc.next();
        String sql;
        sql = "insert into info values(" + id + ",'" + name + "'," + ws + ",'" + addr + "')";
        stmt.executeUpdate(sql);
        System.out.println("record inserted");

        // Update Record
        System.out.println("Update Table ");
        System.out.println("Enter the id ");
        int id1 = sc.nextInt();
        sql = "update info set workforce = 20 where id = '" + id1 + "'";
        stmt.executeUpdate(sql);
        System.out.println("record updated");

        conn.close();

    }

}
