/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise;

import java.sql.*;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {

        // Load database driver in memory

        Class.forName("org.postgresql.Driver");
        System.out.println("Driver Loaded");

        Connection conn;
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test", "postgres", "root");

        System.out.println("Connection Done");

        Statement stmt = conn.createStatement();
        String sql;

        sql = "select * from student";

        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            System.out.println(rs.getInt("id"));
            System.out.println(rs.getString("name"));
        }

        conn.close();

    }
}
